// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation.Cinema.Api.Shared.Persistence;

#nullable disable

namespace Reservation.Cinema.Api.Shared.Persistence.Migrations
{
    [DbContext(typeof(CinemaReservationDbContext))]
    [Migration("20250601094433_change dbset hall")]
    partial class changedbsethall
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservation.Cinema.Api.Models.Domain.CinemaHall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CinemaHalls");
                });

            modelBuilder.Entity("Reservation.Cinema.Api.Models.Domain.CinemaHall", b =>
                {
                    b.OwnsMany("Reservation.Cinema.Api.Models.Domain.Seat", "Seats", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("CinemaHallId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("CinemaHallId");

                            b1.ToTable("Seats");

                            b1.WithOwner()
                                .HasForeignKey("CinemaHallId");

                            b1.OwnsMany("Reservation.Cinema.Api.Models.Domain.SeatReservation", "SeatReservations", b2 =>
                                {
                                    b2.Property<int>("SeatId")
                                        .HasColumnType("int");

                                    b2.Property<DateTime>("From")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("To")
                                        .HasColumnType("datetime2");

                                    b2.Property<int>("Id")
                                        .HasColumnType("int");

                                    b2.HasKey("SeatId", "From", "To");

                                    b2.ToTable("SeatReservations");

                                    b2.WithOwner("Seat")
                                        .HasForeignKey("SeatId");

                                    b2.Navigation("Seat");
                                });

                            b1.Navigation("SeatReservations");
                        });

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
